// <auto-generated />
using FetchWebapi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FetchWebapi.Migrations
{
    [DbContext(typeof(Appdbcontext))]
    [Migration("20240203093702_initial migrations")]
    partial class initialmigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FetchWebapi.Model.LaptopDetails", b =>
                {
                    b.Property<int>("LaptopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LaptopName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LaptopId");

                    b.ToTable("LaptopDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
