version: '3.4'
volumes:
  datafiles:

services:

  database:

    image: mysql:8.0.22

    ports:
      - "3307:3307"

    volumes:
      - datafiles:/var/lib/mysql
      - "~/sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
  
    environment: 
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: root
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: DockerLaptopSystem
  #Api  Service
  createwebapi:
    build:
      context: ./createwebapi
   
      dockerfile: Dockerfile
    
    depends_on: 
      - database
   
    ports:
      - "5000:80"
    restart: always

    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development

       #Api  Service
  fetchwebapi:
    build:
      context: ./fetchwebapi
      
      dockerfile: Dockerfile

    depends_on: 
      - database
  
    ports:
      - "5001:80"
    restart: always
  
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development
